### ISSUE TITLE
How do you graph the smoke ping in Grafana?

### ISSUE THREAD

**Issue by kaihendry** [SuperQ/smokeping_prober#13]
https://s.natalian.org/2019-03-06/smokeping.mp4

**Comment by DevOps-Dad** [comment]
I have also been trying with little success to reproduce that really cool Grafana dashboard.  Any insights would be much appreciated.  Thanks also for creating this exporter.  I love it.

**Comment by zloo** [comment]
I did something similar for a talk in february, maybe try importing these dashboards and change the metric names, https://github.com/CloudNativePrague/meetups/tree/master/2019/02_February/prometheus-histograms-grafana-heatmaps

**Comment by paulfantom** [comment]
I am using this one: https://gist.github.com/paulfantom/959d4150f4610ed332aa09cc911f8e82

@SuperQ do you want something like above as a jsonnet mixin somewhere in this repo?

**Comment by SuperQ** [comment]
Sure, we could either include the full json, or go mixin.

**Comment by paulfantom** [comment]
Ok, so lets start small with a simple dashboard and we can always change it to jsonnet if it gets too complicated. Here is a PR: #28

**Comment by kaihendry** [comment]
Would be nice to see a screenshot. My concern is that it doesn't match the legendary https://oss.oetiker.ch/smokeping/stats.en.html i.e. showing smoke for unstable connections and such.

**Comment by paulfantom** [comment]
![Screenshot_20191112_094700](https://user-images.githubusercontent.com/3531758/68656053-65f03980-0531-11ea-9abc-e74388caa9c7.png)

**Comment by SuperQ** [comment]
I've got a few more ideas for the dashboard. Once I have it worked up, I'll update the screenshot in the README based on the new dashboard.
