### ISSUE TITLE
Feature request: - Different bucket size for different hosts / hostgroups

### ISSUE THREAD

**Issue by Nachtfalkeaw** [SuperQ/smokeping_prober#134]
Hello,

I use smoke_ping to probe several different destinations. Some are reachable with low response times and others in general have higher response times.

It would be nice to have the possibility to define different buckets sizes for different hosts or groups of hosts - similar to to interval, packet size and so on.

This would allow me to group hosts with similar expected latencies and define fine grained buckets so that it is possible differentiate the different pings easily but not to use too many buckts which need to scale on the Y-axis.

**Comment by SuperQ** [comment]
This is not possible due to the way metrics collection works.

You're better of switching collection to native histograms.
