### ISSUE TITLE
Make pinging IPv4 / IPv6 / both configurable

### ISSUE THREAD

**Issue by zloo** [SuperQ/smokeping_prober#14]
There's no way to configure whether we want to ping ipv4, ipv6 or both.

**Comment by SuperQ** [comment]
I filed https://github.com/sparrc/go-ping/issues/64 upstream. It should be pretty easy to implement.

**Comment by Fluepke** [comment]
When https://github.com/SuperQ/smokeping_prober/pull/40 gets merged, all (legacy and current version) of IP addresses specified in DNS for a given FQDN will be pinged.

**Comment by edgarasg** [comment]
Any news on this?
