### ISSUE TITLE
Create github release for 0.7.3

### ISSUE THREAD

**Issue by pavelzw** [SuperQ/smokeping_prober#144]
I saw that you released 0.7.3 on https://quay.io/superq/smokeping-prober and that there is a changelog for 0.7.3 [here](https://github.com/SuperQ/smokeping_prober/blob/master/CHANGELOG.md) but a GitHub release is still missing.

**Comment by SuperQ** [comment]
Yes, sorry, I was waiting for CI to publish the artifacts and got distracted by other things.
