### ISSUE TITLE
Inspect packet TTL

### ISSUE THREAD

**Issue by SuperQ** [SuperQ/smokeping_prober#19]
The upstream go-ping library now records packet TTL. It would be good to collect this TTL.

Options for this:
* Record the last packet's TTL.
* Observe the TTL as a histogram.

I think the histogram is either not granular enough, or too much cardinality.

So I'm leaning towards just tracking the last TTL, and exposing that as a single metric per pinger.

**Comment by zloo** [comment]
Agreed with tracking just the last TTL. I don't think this value will change much, so recording it as a histogram doesn't make much sense to me. This would be a rather easy thing to add, and if someone has a use case for TTL histogram, they can create a ticket in the future.
