### ISSUE TITLE
is it possible to introduce packet size flag

### ISSUE THREAD

**Issue by from88** [SuperQ/smokeping_prober#2]
Hello,

Seems it's a good project and feature that everyone wants. But maybe it's possible to introduce packet size flag, also ? Thanks

**Comment by SuperQ** [comment]
Yes, was on the TODO list in my head as well. Thanks for writing it down.

I was doing some testing and I think the upstream go-ping library broke the `Size` feature. Something strange is going on with the new JSON packet tracking code.
