### ISSUE TITLE
Any way I can tell how many packets timed out?

### ISSUE THREAD

**Issue by mhansen** [SuperQ/smokeping_prober#24]
I'm guessing not, because the underlying library doesn't expose a callback?

I'm just looking at my graphs and would kinda expect some timeouts (maybe represented as +Inf?) but I'm not seeing any.

**Comment by SuperQ** [comment]
The underlying library doesn't really deal with timeouts very well. There is some work to deal with that.

You can find out lost packets with `smokeping_requests_total - smokeping_response_duration_seconds_count`.

**Comment by mhansen** [comment]
Cheers, that worked a treat, graphing

rate(smokeping_requests_total[1m]) -
rate(smokeping_response_duration_seconds_count[1m])
