### ISSUE TITLE
Allow specifying source IP for pings

### ISSUE THREAD

**Issue by jtackaberry** [SuperQ/smokeping_prober#26]
I run the original smokeping on a Linux router with multiple WAN uplinks and am interested in replacing it with smokeping_prober for Prom integration.

For that use-case, I need to be able to specify the source IP independently for the various ping targets in order to test the different WAN paths.

It looks like [go-ping does support that](https://github.com/sparrc/go-ping/pull/58) so it's just a matter of exposing some means of specifying source addresses in smokeping_prober.

**Comment by SuperQ** [comment]
Seems like a good feature idea to me.
