### ISSUE TITLE
Dockerfile issues

### ISSUE THREAD

**Issue by ufou** [SuperQ/smokeping_prober#27]
I'd really like to use this tool on k8s, when I try to build the docker image using the Dockerfile, I get: 
```
Step 1/5 : FROM quay.io/prometheus/busybox:glibc
 ---> 6bf7fc538cdd
Step 2/5 : LABEL maintainer="Ben Kochie <superq@gmail.com>"
 ---> Using cache
 ---> 62f730c141ee
Step 3/5 : COPY smokeping_prober /bin/smokeping_prober
COPY failed: stat /var/lib/docker/tmp/docker-builder478249608/smokeping_prober: no such file or directory
```

Perhaps it's not expected to work?

**Comment by zloo** [comment]
@ufou I think you have to first do `go build`, and then you can build the docker image.

If you're doing it in some sort of CI/CD pipeline (as i'd guess from the COPY failed line), you have to somehow clone the repo, go build, and then build the docker image

**Comment by ufou** [comment]
🤦‍♂  @zloo many thanks for the response! I had indeed not added the `go build` command as a CI step!

**Comment by SuperQ** [comment]
Thanks for the reminder, I should add a CI pipeline to publish an official docker image of this project. :smile:
