### ISSUE TITLE
Question on Prometheus integration

### ISSUE THREAD

**Issue by satishrao84** [SuperQ/smokeping_prober#33]
Hi,

I've created the daemonset that runs your smokeping_prober on all nodes in the cluster. I can see the metrics exposed on port 9374. Now what? Do I need to integrate prometheus or do I point Grafana at this directly?

**Comment by SuperQ** [comment]
You need to configure Prometheus to scrape the them.

**Comment by satishrao84** [comment]
Hi,

If I have a daemonset which is running the smokeping_prober on all nodes in the cluster - because I need to see the ping stats from each node to every other node. 

- How do I create a prometheus  deployment that would scrape the metrics from all the pods that the daemonset spins up ? - because the pod names are not known beforehand. 

- How would I configure the pod names to match that of the node that it lies on? How did you do deployment?
