### ISSUE TITLE
latency and packet loss in the graph

### ISSUE THREAD

**Issue by gaardam** [SuperQ/smokeping_prober#38]
Hello,
I'm trying to re-create a smokping graph where it visualizes latency and packet loss on the same graph.
 
The example.png you have is not labelled, but it looks similar to a smokeping graph, in that the white boxes could represent the average latency when there is no packet loss, and the colored boxes could represent the average latency when there is packet loss - with the color representing the amount of packet loss in that interval. Is that the case?

If so, I have been unable to recreate your graph.

the grafana dashboard.json with the query, sum(rate(smokeping_response_duration_seconds_bucket{instance=~\"$prober\",host=\"$target\"}[5m])) by (le) - looks like it will only represent latency - not packet loss.

It looks like the way to calculate packet loss, would be to subtract smokeping_response_duration_seconds_count from smokeping_requests_total?

So far, I've been unable to produce a satisfactory graph that shows packet loss per interval. Is it possible?

**Comment by SuperQ** [comment]
The heatmap does not represent packet loss, only spread of latency. You would need a separate graph for packet loss.
