### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by gsstark** [SuperQ/smokeping_prober#41]
Is there any documentation for this exporter? It looks cool but I have a bunch of questions and can't find any docs to answer them.

1) Does it only do ICMP pings or can I do TCP connection requests to a port and measure how long it takes to get a connection established? Can I do other types of pings like nmap does?

2) From the README it looks like there are no metrics for the number of connection refused or other errors? At least there are none listed. Are they printed in the logs?

3) Can you configure multiple ports and hosts and get multiple time series? Or are you expected to run many instances of smokeping_prober? What does it do if t gets back multiple responses from pings?

As I said, this looks like a tool that might be super userful so it would be awesome but it's hard to tell without docs.

**Comment by SuperQ** [comment]
* It currently only does ICMP.
* Additional error counters would have to come from the ping library.
* Since it only does ICMP, no ports are involved. You can specify multiple ICMP targets and it will label metrics for each one.
