### ISSUE TITLE
Use a configuration file containing a list of hosts?

### ISSUE THREAD

**Issue by isuldor** [SuperQ/smokeping_prober#50]
This is a feature request, unless I'm neglecting a simple and obvious way to accomplish it. I would like to maintain a plain text list of targets, and pass that configuration file as a parameter to smokeping_prober.  My current implementation was to write a systemd service unit. While that works for my 20+ targets, it feels a bit sloppy!

**Comment by SuperQ** [comment]
There are several related features that I plan to tackle at the same time.
* Tagging hosts
* Dynamic reload
* Config file.

Some of it's documented here: https://github.com/SuperQ/smokeping_prober/issues/35#issuecomment-744562630
