### ISSUE TITLE
Counter stops at 65535

### ISSUE THREAD

**Issue by jvandenbroek** [SuperQ/smokeping_prober#51]
Since i've pulled the new smokeping docker a few days ago, it seems to stop when 1 counter reaches the magical uint16 number? Seems to happen on the first hit, other pingers that are not there yet also stall. Example:

`smokeping_response_duration_seconds_bucket{host="192.168.x.x",ip="192.168.x.x",le="0.0005"} 28107                            
smokeping_response_duration_seconds_bucket{host="192.168.x.x",ip="192.168.x.x",le="0.00125"} 64943                           
smokeping_response_duration_seconds_bucket{host="192.168.x.x",ip="192.168.x.x",le="0.0025"} 65391                            
smokeping_response_duration_seconds_bucket{host="192.168.x.x",ip="192.168.x.x",le="0.005"} 65481                             
smokeping_response_duration_seconds_bucket{host="192.168.x.x",ip="192.168.x.x",le="0.01"} 65511                              
smokeping_response_duration_seconds_bucket{host="192.168.x.x",ip="192.168.x.x",le="0.015"} 65522                             
smokeping_response_duration_seconds_bucket{host="192.168.x.x",ip="192.168.x.x",le="0.02"} 65529                              
smokeping_response_duration_seconds_bucket{host="192.168.x.x",ip="192.168.x.x",le="0.025"} 65531                             
smokeping_response_duration_seconds_bucket{host="192.168.x.x",ip="192.168.x.x",le="0.05"} 65533                              
smokeping_response_duration_seconds_bucket{host="192.168.x.x",ip="192.168.x.x",le="0.075"} 65533                             
smokeping_response_duration_seconds_bucket{host="192.168.x.x",ip="192.168.x.x",le="0.1"} 65533                               
smokeping_response_duration_seconds_bucket{host="192.168.x.x",ip="192.168.x.x",le="0.25"} 65534                              
smokeping_response_duration_seconds_bucket{host="192.168.x.x",ip="192.168.x.x",le="0.5"} 65534                               
smokeping_response_duration_seconds_bucket{host="192.168.x.x",ip="192.168.x.x",le="1"} 65534                                 
smokeping_response_duration_seconds_bucket{host="192.168.x.x",ip="192.168.x.x",le="2"} 65535                                 
smokeping_response_duration_seconds_bucket{host="192.168.x.x",ip="192.168.x.x",le="+Inf"} 65535                              
smokeping_response_duration_seconds_sum{host="192.168.x.x",ip="192.168.x.x"} 38.20973433999988                               
smokeping_response_duration_seconds_count{host="192.168.x.x",ip="192.168.x.x"} 65535 `

Also build a binary myself (golang 1.15.8), same result. Couldn't figure out what commit caused this, maybe something in go-ping library?

**Comment by SuperQ** [comment]
Interesting, it looks like the sending keeps going, but the response buckets stop counting.

**Comment by SuperQ** [comment]
Oh yea, ICMP sequence numbers are only 16 bits. I suppose the library should wrap the sequence number when it hits 65535.
