### ISSUE TITLE
The --buckets argument is ignored

### ISSUE THREAD

**Issue by mlazowik** [SuperQ/smokeping_prober#64]
Since https://github.com/SuperQ/smokeping_prober/commit/1ca438544dd5ae74dd814118b44899216561d00b#diff-f1c80b360812fd52bef43d56f3c4ef40853f02711810857332ccedfd9f463f79

**Comment by SuperQ** [comment]
Oops!

**Comment by taintedkernel** [comment]
Thanks for the release!  Also just wanted to point out, it seems there a credential issue on the CI image pipeline: https://app.circleci.com/pipelines/github/SuperQ/smokeping_prober/143/workflows/ea911852-79cd-49d7-a08f-b1a8f399379d/jobs/317
