### ISSUE TITLE
Dies if name resolution fails

### ISSUE THREAD

**Issue by lindhor** [SuperQ/smokeping_prober#68]
Starting smokeping_prober with a config containing targets that fail name resolution causes it to stop the process with the message
```
ts=2022-05-01T00:15:36.709Z caller=main.go:115 level=info msg="Starting smokeping_prober" version="(version=0.5.2, branch=HEAD, revision=8b043152f9ccbaf61345d77758bb5069a02635a6)"
ts=2022-05-01T00:15:36.709Z caller=main.go:116 level=info msg="Build context" build_context="(go=go1.17.8, user=root@5cbe1f02c0a8, date=20220317-11:16:31)"

ts=2022-05-01T00:15:47.759Z caller=main.go:185 level=error msg="failed to resolve pinger" error="lookup xxx: no such host"
```
It would in my opinion be better if it continued pinging other targets defined (i.e. the ones that are resolvable or specified via IP instead of name).

Probably switching to break instead of return at https://github.com/SuperQ/smokeping_prober/blob/master/main.go#L149 ?

I'm running on Windows if that matters.

**Comment by SuperQ** [comment]
That would be a very bad behavior, as you have silent partial failure. I prefer [fail-fast](https://en.wikipedia.org/wiki/Fail-fast).

**Comment by lindhor** [comment]
Thanks for the quick feedback. After posting this I started to understand that name resolution is only done once at process startup, is that correct? In that case I fully agree with fail-fast.

If you would do name resolution at each interval or regularly I think you would run into temporary DNS issues that would stop the whole process. That would mean that you would loose valuable stats for other targets. One approach to handle silent failures of some targets could be to include a metric with some info indicating its not possible to resolve.

**Comment by SuperQ** [comment]
Yea, there's no re-resolution supported yet. I eventually plan to support SIGHUP to re-read the config. I don't think I want to support periodic re-resolution. But at reload time it would be reasonable, since my likely reload approach would be to restart all probes.

At that point it would be more appropriate to not fail and provide lookup failure as a metric.
