### ISSUE TITLE
Possibility to specify the packet count per interval

### ISSUE THREAD

**Issue by Daryes** [SuperQ/smokeping_prober#78]
Hello,
thanks for building this nice tool.

My request would be to have a `--count` option to allow to specify the number of ping sent for a single `--interval`.
Default would be `1`  which would keep the actual behavior without interference.  

Usually, when something cannot be reached or has connection troubles, it won't be just one time, it'll stay for multiples minutes, if not more.
That's a personal opinion, but for many cases, it would be more suitable to send 3-5 pings in a row, each 30sec (or each minute) to check the availability than pinging continuously each second.
The number of pings itself would also allow to account for network load and the possibility of packet drop due to the lower icmp priority on network hardware.

**Comment by SuperQ** [comment]
That's not how this exporter is designed to work. And doesn't actually solve the problem you're suggesting.

ICMP is only really good for end-to-end signals, not target signals.

This prober is designed to send a smooth set of continuous probes, at a regular interval.  Then you scrape it at a sampling interval.

What you are suggesting doesn't actually make sense. It's actually a flaw in the original smokeping implementation, due the primitive design of the original.
