### ISSUE TITLE
Docker config location?

### ISSUE THREAD

**Issue by mcdent** [SuperQ/smokeping_prober#80]
Hi,
I'm looking for info on the name of the config file and location of said file, so I can export a volume.
Thanks
Mike

**Comment by SuperQ** [comment]
There is no config flie by default, so you can map it to wherever you want and pass the location in as an argument.

**Comment by v4rakh** [comment]
Stumbled on it by accident, so I guess @mcdent is looking for something like the following in a docker-compose setup?!

```
...
volumes:
   - ./config.yml:/etc/smokeping_prober.yml
command: --config.file=/etc/smokeping_prober.yml
```
